* 修复5.4.6报错 memory_leak_checker.c(153,4): error C2440: 'initializing'… (#1085)
* * 修复5.4.6报错 memory_leak_checker.c(153,4): error C2440: 'initializing': cannot convert from 'StkIdRel' to 'TValue *'

* * 修复5.4.6报错 memory_leak_checker.c(153,4) 兼容5.4.1